apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: finch-production
  labels:
    app: finch
    component: backend
type: Opaque
data:
  # Django secret key - generate with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
  # echo -n 'django-insecure-production-key-change-this-in-production-2024-secure-random-key' | base64
  django-secret-key: ZGphbmdvLWluc2VjdXJlLXByb2R1Y3Rpb24ta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24tMjAyNC1zZWN1cmUtcmFuZG9tLWtleQ==
  
  # JWT secret for token signing
  # echo -n 'jwt-secret-key-for-token-signing-2024-production' | base64
  jwt-secret-key: and0LXNlY3JldC1rZXktZm9yLXRva2VuLXNpZ25pbmctMjAyNC1wcm9kdWN0aW9u
  
  # Email configuration secrets
  # echo -n 'smtp_username' | base64
  email-username: c210cF91c2VybmFtZQ==
  # echo -n 'smtp_password' | base64
  email-password: c210cF9wYXNzd29yZA==
  
  # AWS/Cloud storage credentials (if using)
  # echo -n 'AWS_ACCESS_KEY_ID' | base64
  aws-access-key-id: QVDTX0FDQ0VTU19LRVlfSUQ=
  # echo -n 'AWS_SECRET_ACCESS_KEY' | base64
  aws-secret-access-key: QVDTX1NFQ1JFVF9BQ0NFU1NfS0VZ
  
  # Sentry DSN for error tracking
  # echo -n 'https://your-sentry-dsn@sentry.io/project-id' | base64
  sentry-dsn: aHR0cHM6Ly95b3VyLXNlbnRyeS1kc25Ac2VudHJ5LmlvL3Byb2plY3QtaWQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: finch-staging
  labels:
    app: finch
    component: backend
    environment: staging
type: Opaque
data:
  # Staging application secrets
  django-secret-key: ZGphbmdvLWluc2VjdXJlLXN0YWdpbmcta2V5LWNoYW5nZS10aGlzLWluLXN0YWdpbmctMjAyNA==
  jwt-secret-key: and0LXNlY3JldC1rZXktZm9yLXRva2VuLXNpZ25pbmctMjAyNC1zdGFnaW5n
  email-username: c210cF91c2VybmFtZV9zdGFnaW5n
  email-password: c210cF9wYXNzd29yZF9zdGFnaW5n
  aws-access-key-id: QVDTX0FDQ0VTU19LRVlfSURfU1RBR0lORw==
  aws-secret-access-key: QVDTX1NFQ1JFVF9BQ0NFU1NfS0VZX1NUQUdJTkc=
  sentry-dsn: aHR0cHM6Ly95b3VyLXNlbnRyeS1kc24tc3RhZ2luZ0BzZW50cnkuaW8vcHJvamVjdC1pZA==
