apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: finch-production
  labels:
    app: finch
    component: database
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'fleetdb' | base64
  database-name: ZmxlZXRkYg==
  # echo -n 'roy77' | base64
  database-user: cm95Nzc=
  # echo -n 'asdf1234@77' | base64
  database-password: YXNkZjEyMzRANzc=
  # Connection string format: postgresql://user:password@host:port/database
  # echo -n 'postgresql://roy77:asdf1234@77@postgresql:5432/fleetdb' | base64
  database-url: cG9zdGdyZXNxbDovL3JveTc3OmFzZGYxMjM0QDc3QHBvc3RncmVzcWw6NTQzMi9mbGVldGRi
---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: finch-staging
  labels:
    app: finch
    component: database
    environment: staging
type: Opaque
data:
  # Staging database credentials
  database-name: ZmxlZXRkYl9zdGFnaW5n  # fleetdb_staging
  database-user: cm95Nzc=  # roy77
  database-password: YXNkZjEyMzRANzc=  # asdf1234@77
  database-url: cG9zdGdyZXNxbDovL3JveTc3OmFzZGYxMjM0QDc3QHBvc3RncmVzcWw6NTQzMi9mbGVldGRiX3N0YWdpbmc=
