apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: finch-monitoring
  labels:
    app: monitoring
    component: observability
type: Opaque
data:
  # Grafana admin credentials
  # echo -n 'admin' | base64
  grafana-admin-username: YWRtaW4=
  # echo -n 'secure_grafana_password_2024' | base64
  grafana-admin-password: c2VjdXJlX2dyYWZhbmFfcGFzc3dvcmRfMjAyNA==
  
  # Prometheus basic auth (if enabled)
  # echo -n 'prometheus_user' | base64
  prometheus-username: cHJvbWV0aGV1c191c2Vy
  # echo -n 'prometheus_password_2024' | base64
  prometheus-password: cHJvbWV0aGV1c19wYXNzd29yZF8yMDI0
  
  # AlertManager webhook URLs
  # echo -n 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK' | base64
  slack-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvWU9VUi9TTEFUL1dFQkhPT0s=
  
  # PagerDuty integration key
  # echo -n 'pagerduty_integration_key' | base64
  pagerduty-key: cGFnZXJkdXR5X2ludGVncmF0aW9uX2tleQ==
  
  # Email SMTP settings for alerts
  # echo -n 'alerts@finch.example.com' | base64
  smtp-username: YWxlcnRzQGZpbmNoLmV4YW1wbGUuY29t
  # echo -n 'smtp_password_for_alerts' | base64
  smtp-password: c210cF9wYXNzd29yZF9mb3JfYWxlcnRz
