apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: finch-production
  labels:
    app: finch
    component: payment
type: Opaque
data:
  # Stripe API keys
  # echo -n 'pk_live_stripe_publishable_key_here' | base64
  stripe-publishable-key: cGtfbGl2ZV9zdHJpcGVfcHVibGlzaGFibGVfa2V5X2hlcmU=
  # echo -n 'sk_live_stripe_secret_key_here' | base64
  stripe-secret-key: c2tfbGl2ZV9zdHJpcGVfc2VjcmV0X2tleV9oZXJl
  # echo -n 'whsec_stripe_webhook_secret_here' | base64
  stripe-webhook-secret: d2hzZWNfc3RyaXBlX3dlYmhvb2tfc2VjcmV0X2hlcmU=
  
  # PayPal credentials (if used)
  # echo -n 'paypal_client_id' | base64
  paypal-client-id: cGF5cGFsX2NsaWVudF9pZA==
  # echo -n 'paypal_client_secret' | base64
  paypal-client-secret: cGF5cGFsX2NsaWVudF9zZWNyZXQ=
  
  # Paystack credentials (if used)
  # echo -n 'pk_live_paystack_public_key' | base64
  paystack-public-key: cGtfbGl2ZV9wYXlzdGFja19wdWJsaWNfa2V5
  # echo -n 'sk_live_paystack_secret_key' | base64
  paystack-secret-key: c2tfbGl2ZV9wYXlzdGFja19zZWNyZXRfa2V5
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: finch-staging
  labels:
    app: finch
    component: payment
    environment: staging
type: Opaque
data:
  # Stripe test keys for staging
  stripe-publishable-key: cGtfdGVzdF9zdHJpcGVfcHVibGlzaGFibGVfa2V5X2hlcmU=  # pk_test_stripe_publishable_key_here
  stripe-secret-key: c2tfdGVzdF9zdHJpcGVfc2VjcmV0X2tleV9oZXJl  # sk_test_stripe_secret_key_here
  stripe-webhook-secret: d2hzZWNfc3RyaXBlX3dlYmhvb2tfc2VjcmV0X3Rlc3Q=  # whsec_stripe_webhook_secret_test
  paypal-client-id: cGF5cGFsX2NsaWVudF9pZF90ZXN0  # paypal_client_id_test
  paypal-client-secret: cGF5cGFsX2NsaWVudF9zZWNyZXRfdGVzdA==  # paypal_client_secret_test
  paystack-public-key: cGtfdGVzdF9wYXlzdGFja19wdWJsaWNfa2V5  # pk_test_paystack_public_key
  paystack-secret-key: c2tfdGVzdF9wYXlzdGFja19zZWNyZXRfa2V5  # sk_test_paystack_secret_key
