apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: finch-production
  labels:
    app: finch
    component: cache
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'finch_redis_pass_prod_2024' | base64
  redis-password: ZmluY2hfcmVkaXNfcGFzc19wcm9kXzIwMjQ=
  # echo -n 'redis://:finch_redis_pass_prod_2024@redis:6379/0' | base64
  redis-url: cmVkaXM6Ly86ZmluY2hfcmVkaXNfcGFzc19wcm9kXzIwMjRAcmVkaXM6NjM3OS8w
  # echo -n 'redis://redis:6379/0' | base64 (for testing without auth)
  redis-url-no-auth: cmVkaXM6Ly9yZWRpczozNjc5LzA=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: finch-staging
  labels:
    app: finch
    component: cache
    environment: staging
type: Opaque
data:
  # Staging Redis credentials
  redis-password: ZmluY2hfcmVkaXNfcGFzc19zdGFnaW5nXzIwMjQ=  # finch_redis_pass_staging_2024
  redis-url: cmVkaXM6Ly86ZmluY2hfcmVkaXNfcGFzc19zdGFnaW5nXzIwMjRAcmVkaXM6NjM3OS8w  # redis://:finch_redis_pass_staging_2024@redis:6379/0
