apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-production
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /mnt/data/postgres-production
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-staging
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast-ssd
  hostPath:
    path: /mnt/data/postgres-staging
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-production
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /mnt/data/redis-production
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-staging
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast-ssd
  hostPath:
    path: /mnt/data/redis-staging
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-production
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/media-production
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-staging
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /mnt/data/media-staging
